// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>WebDAVdotNet</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace WebDAVdotNet.Schemas
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class activelock
    {

        private lockscope lockscopeField;

        private locktype locktypeField;

        private string depthField;

        private System.Xml.XmlNode ownerField;

        private string timeoutField;

        private List<string> locktokenField;

        public activelock()
        {
            this.locktokenField = new List<string>();
            this.locktypeField = new locktype();
            this.lockscopeField = new lockscope();
        }

        public lockscope lockscope
        {
            get
            {
                return this.lockscopeField;
            }
            set
            {
                this.lockscopeField = value;
            }
        }

        public locktype locktype
        {
            get
            {
                return this.locktypeField;
            }
            set
            {
                this.locktypeField = value;
            }
        }

        public string depth
        {
            get
            {
                return this.depthField;
            }
            set
            {
                this.depthField = value;
            }
        }

        public System.Xml.XmlNode owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }

        public string timeout
        {
            get
            {
                return this.timeoutField;
            }
            set
            {
                this.timeoutField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("href", IsNullable = false)]
        public List<string> locktoken
        {
            get
            {
                return this.locktokenField;
            }
            set
            {
                this.locktokenField = value;
            }
        }
    }

    public partial class lockscope
    {

        private object itemField;

        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    public partial class exclusive
    {
    }

    public partial class shared
    {
    }

    public partial class locktype
    {

        private write writeField;

        public locktype()
        {
            this.writeField = new write();
        }

        public write write
        {
            get
            {
                return this.writeField;
            }
            set
            {
                this.writeField = value;
            }
        }
    }

    public partial class write
    {
    }

    public partial class lockentry
    {

        private lockscope lockscopeField;

        private locktype locktypeField;

        public lockentry()
        {
            this.locktypeField = new locktype();
            this.lockscopeField = new lockscope();
        }

        public lockscope lockscope
        {
            get
            {
                return this.lockscopeField;
            }
            set
            {
                this.lockscopeField = value;
            }
        }

        public locktype locktype
        {
            get
            {
                return this.locktypeField;
            }
            set
            {
                this.locktypeField = value;
            }
        }
    }

    public partial class lockinfo
    {

        private lockscope lockscopeField;

        private locktype locktypeField;

        private System.Xml.XmlNode ownerField;

        public lockinfo()
        {
            this.locktypeField = new locktype();
            this.lockscopeField = new lockscope();
        }

        public lockscope lockscope
        {
            get
            {
                return this.lockscopeField;
            }
            set
            {
                this.lockscopeField = value;
            }
        }

        public locktype locktype
        {
            get
            {
                return this.locktypeField;
            }
            set
            {
                this.locktypeField = value;
            }
        }

        public System.Xml.XmlNode owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
    }

    public partial class locktoken
    {

        private List<string> hrefField;

        public locktoken()
        {
            this.hrefField = new List<string>();
        }

        public List<string> href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
    }

    public partial class link
    {

        private List<string> srcField;

        private List<string> dstField;

        public link()
        {
            this.dstField = new List<string>();
            this.srcField = new List<string>();
        }

        public List<string> src
        {
            get
            {
                return this.srcField;
            }
            set
            {
                this.srcField = value;
            }
        }

        public List<string> dst
        {
            get
            {
                return this.dstField;
            }
            set
            {
                this.dstField = value;
            }
        }
    }

    public partial class multistatus
    {

        private List<response> responseField;

        private string responsedescriptionField;

        public multistatus()
        {
            this.responseField = new List<response>();
        }

        public List<response> response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }

        public string responsedescription
        {
            get
            {
                return this.responsedescriptionField;
            }
            set
            {
                this.responsedescriptionField = value;
            }
        }
    }

    public partial class response
    {

        private List<string> hrefField;

        private List<object> itemsField;

        private System.Xml.XmlElement errorField;

        private string responsedescriptionField;

        public response()
        {
            this.itemsField = new List<object>();
            this.hrefField = new List<string>();
        }

        public List<string> href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        public System.Xml.XmlElement error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        public string responsedescription
        {
            get
            {
                return this.responsedescriptionField;
            }
            set
            {
                this.responsedescriptionField = value;
            }
        }
    }

    public partial class propstat
    {

        private List<object> propField;

        private string statusField;

        private System.Xml.XmlElement errorField;

        private string responsedescriptionField;

        public propstat()
        {
            this.propField = new List<object>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("", typeof(System.Xml.XmlElement), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("creationdate", typeof(creationdate), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayname", typeof(displayname), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontentlanguage", typeof(getcontentlanguage), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontentlength", typeof(getcontentlength), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontenttype", typeof(getcontenttype), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getetag", typeof(getetag), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getlastmodified", typeof(getlastmodified), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lockdiscovery", typeof(lockdiscovery), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resourcetype", typeof(resourcetype), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("supportedlock", typeof(supportedlock), IsNullable = false)]
        public List<object> prop
        {
            get
            {
                return this.propField;
            }
            set
            {
                this.propField = value;
            }
        }

        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public System.Xml.XmlElement error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        public string responsedescription
        {
            get
            {
                return this.responsedescriptionField;
            }
            set
            {
                this.responsedescriptionField = value;
            }
        }
    }

    public partial class creationdate
    {

        private List<string> textField;

        public creationdate()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class displayname
    {

        private List<string> textField;

        public displayname()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class getcontentlanguage
    {

        private List<string> textField;

        public getcontentlanguage()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class getcontentlength
    {

        private List<string> textField;

        public getcontentlength()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class getcontenttype
    {

        private List<string> textField;

        public getcontenttype()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class getetag
    {

        private List<string> textField;

        public getetag()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class getlastmodified
    {

        private List<string> textField;

        public getlastmodified()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class lockdiscovery
    {

        private List<activelock> activelockField;

        public lockdiscovery()
        {
            this.activelockField = new List<activelock>();
        }

        public List<activelock> activelock
        {
            get
            {
                return this.activelockField;
            }
            set
            {
                this.activelockField = value;
            }
        }
    }

    public partial class resourcetype
    {

        private collection collectionField;

        private List<System.Xml.XmlElement> anyField;

        public resourcetype()
        {
            this.anyField = new List<System.Xml.XmlElement>();
            this.collectionField = new collection();
        }

        public collection collection
        {
            get
            {
                return this.collectionField;
            }
            set
            {
                this.collectionField = value;
            }
        }

        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 1)]
        public List<System.Xml.XmlElement> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    public partial class collection
    {
    }

    public partial class supportedlock
    {

        private List<lockentry> lockentryField;

        public supportedlock()
        {
            this.lockentryField = new List<lockentry>();
        }

        public List<lockentry> lockentry
        {
            get
            {
                return this.lockentryField;
            }
            set
            {
                this.lockentryField = value;
            }
        }
    }

    public partial class prop
    {

        private List<object> itemsField;

        public prop()
        {
            this.itemsField = new List<object>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class propertybehavior
    {

        private object itemField;

        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    public partial class keepalive
    {

        private List<string> hrefField;

        private List<string> textField;

        public keepalive()
        {
            this.textField = new List<string>();
            this.hrefField = new List<string>();
        }

        public List<string> href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class omit
    {
    }

    public partial class propertyupdate
    {

        private List<object> itemsField;

        public propertyupdate()
        {
            this.itemsField = new List<object>();
        }

        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class remove
    {

        private List<object> propField;

        public remove()
        {
            this.propField = new List<object>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("", typeof(System.Xml.XmlElement), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("creationdate", typeof(creationdate), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayname", typeof(displayname), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontentlanguage", typeof(getcontentlanguage), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontentlength", typeof(getcontentlength), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontenttype", typeof(getcontenttype), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getetag", typeof(getetag), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getlastmodified", typeof(getlastmodified), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lockdiscovery", typeof(lockdiscovery), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resourcetype", typeof(resourcetype), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("supportedlock", typeof(supportedlock), IsNullable = false)]
        public List<object> prop
        {
            get
            {
                return this.propField;
            }
            set
            {
                this.propField = value;
            }
        }
    }

    public partial class set
    {

        private List<object> propField;

        public set()
        {
            this.propField = new List<object>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("", typeof(System.Xml.XmlElement), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("creationdate", typeof(creationdate), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayname", typeof(displayname), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontentlanguage", typeof(getcontentlanguage), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontentlength", typeof(getcontentlength), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getcontenttype", typeof(getcontenttype), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getetag", typeof(getetag), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getlastmodified", typeof(getlastmodified), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lockdiscovery", typeof(lockdiscovery), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("resourcetype", typeof(resourcetype), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("supportedlock", typeof(supportedlock), IsNullable = false)]
        public List<object> prop
        {
            get
            {
                return this.propField;
            }
            set
            {
                this.propField = value;
            }
        }
    }

    public partial class propfind
    {

        private object itemField;

        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    public partial class allprop
    {
    }

    public partial class propname
    {
    }

    public partial class source
    {

        private List<link> linkField;

        public source()
        {
            this.linkField = new List<link>();
        }

        public List<link> link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }
    }
}
